name: airflow_serial_parallel_dag

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  
jobs:
  upload-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Debug DAG paths
        run: |
          pwd
          ls -R SEQ_AND_PARALLEL_AIRFLOW_DAGS/dags

      - name: Upload Airflow DAG (serial)
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-prod \
            --location asia-east1 \
            --source SEQ_AND_PARALLEL_AIRFLOW_DAGS/dags/airflow_dag_for_serial_task.py

      - name: Upload Airflow DAG (parallel)
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-prod \
            --location asia-east1 \
            --source SEQ_AND_PARALLEL_AIRFLOW_DAGS/dags/airflow_dag_for_parallel_tasks.py
